version: '3.9'

services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: StarGo
      MYSQL_PASSWORD: StarGo
      MYSQL_USER: StarGo
      MYSQL_DATABASE: todolist
